### ISSUE TITLE
open up the browser to the page when `gloria serve` is called

### ISSUE THREAD

**Issue by kevdez** [dvidsilva/gloria#17]
This is a neat little tool I use after I have the Express server begin to listen on port  # whatever.

https://www.npmjs.com/package/open

The result looks something like: 

```javascript
var open = require('open');

// ... some code later... where `app` is the Express app

app.listen(PORT, 'localhost', function() {
  open('http://localhost:' + PORT);
});
```

It would help in opening up the browser automatically as soon as you type `gloria serve`.

**Comment by kevdez** [comment]
I spot a `app.listen()` on https://github.com/dvidsilva/gloria/blob/master/lib/commands/serve.js#L28

I can't set labels to issues, but this would be a great first bug if someone wants to contribute.

**Comment by rodrigih** [comment]
I'll claim/work on this issue.

**Comment by dvidsilva** [comment]
Can we pass a flag to prevent this? because we don't have a watch command, there are two alternatives, either you rebuild in a different terminal or you stop the server and restart it. 

If an user choses the second option they're gonna get a ton of tabs

**Comment by kevdez** [comment]
Is `gloria serve` supposed to be used a few times after the site is done? or multiple times each time there is a new change in the site because of the lack of the `watch` command? I think normally the first thing someone does when they serve a site from their CLI is check on their browser.

Maybe this could be a separate issue. And the command to be `--suppress-browser` or `--silent-serve` or something. That also depends what you want the default option to be: to open by default, or to open by some flag.

**Comment by dvidsilva** [comment]
Ok I can open a separate one, I like the `--suppress-browser` route
